export const commandeurStyles = {
  page: {
    width: "100%",
    display: "flex",
    flexDirection: "column" as const,
    gap: "1.5rem",
  },
  stepperRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: "1rem",
  },
  actionsRow: {
    display: "flex",
    gap: ".5rem",
    flexWrap: "wrap" as const,
  },
  card: {
    position: "relative" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  workspaceSelector: {
    zone: {
      border: "2px dashed #d1d5db",
      borderRadius: ".75rem",
      padding: "2.75rem 1.75rem",
      textAlign: "center" as const,
      background: "#f9fafb",
      display: "flex",
      flexDirection: "column" as const,
      alignItems: "center",
      gap: "1rem",
    },
    hint: {
      fontSize: "1.05rem",
      color: "#6b7280",
      margin: "0 0 .35rem",
    },
    actions: {
      display: "flex",
      gap: ".5rem",
      flexWrap: "wrap" as const,
      justifyContent: "center",
    },
    status: {
      fontSize: ".85rem",
      color: "#4b5563",
    },
    error: {
      fontSize: ".85rem",
      color: "#b91c1c",
      margin: "0",
    },
  },
  workspaceSummary: {
    card: {
      display: "flex",
      flexDirection: "column" as const,
      gap: "1rem",
    },
    headerRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "1rem",
      flexWrap: "wrap" as const,
    },
    controlGroup: {
      display: "flex",
      gap: ".5rem",
      flexWrap: "wrap" as const,
      alignItems: "center",
    },
    extracted: {
      fontSize: ".75rem",
      color: "#4b5563",
      margin: ".25rem 0 0",
    },
  },
  summaryList: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: ".75rem",
    padding: "1rem",
    maxHeight: "280px",
    overflow: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: ".35rem",
  },
  badgeRow: {
    display: "flex",
    gap: ".4rem",
    flexWrap: "wrap" as const,
    alignItems: "center",
  },
  badge: (tone: "neutral" | "success" | "warning" | "error") => {
    const palette: Record<
      "neutral" | "success" | "warning" | "error",
      { bg: string; border: string; color: string }
    > = {
      neutral: { bg: "#f3f4f6", border: "#e5e7eb", color: "#1f2937" },
      success: { bg: "#dcfce7", border: "#86efac", color: "#065f46" },
      warning: { bg: "#fef3c7", border: "#fcd34d", color: "#92400e" },
      error: { bg: "#fee2e2", border: "#fca5a5", color: "#991b1b" },
    };
    const { bg, border, color } = palette[tone];
    return {
      display: "inline-flex",
      alignItems: "center",
      gap: ".4rem",
      borderRadius: "9999px",
      padding: ".15rem .55rem",
      fontSize: ".7rem",
      fontWeight: 600,
      background: bg,
      border: `1px solid ${border}`,
      color,
    } as const;
  },
  list: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".5rem",
    margin: 0,
    padding: 0,
    listStyle: "none" as const,
  },
  listItem: {
    border: "1px solid #e5e7eb",
    borderRadius: ".65rem",
    padding: ".75rem",
    background: "#fff",
    display: "flex",
    flexDirection: "column" as const,
    gap: ".35rem",
  },
  savedPillList: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: ".5rem",
    margin: 0,
    padding: 0,
    listStyle: "none" as const,
  },
  savedPill: (active: boolean) => ({
    display: "flex",
    alignItems: "center",
    gap: ".5rem",
    borderRadius: "9999px",
    border: active ? "1px solid #2563eb" : "1px solid #e5e7eb",
    background: active ? "#dbeafe" : "#f9fafb",
    color: active ? "#1d4ed8" : "#1f2937",
    padding: ".35rem .65rem",
  }),
  savedPillLabel: {
    background: "transparent",
    border: "none",
    color: "inherit",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
    fontSize: ".8rem",
  },
  savedPillActions: {
    display: "flex",
    alignItems: "center",
    gap: ".35rem",
  },
  savedPillActionButton: {
    background: "transparent",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    fontSize: ".85rem",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1.75rem",
    height: "1.75rem",
    borderRadius: "50%",
    transition: "background-color .15s ease",
  },
  statusRow: {
    display: "flex",
    gap: ".5rem",
    flexWrap: "wrap" as const,
    alignItems: "center",
  },
  statusText: {
    color: "#4b5563",
    fontSize: ".8rem",
  },
  logList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".25rem",
    maxHeight: "320px",
    overflow: "auto" as const,
    paddingRight: 4,
  },
  alertList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".25rem",
    maxHeight: "260px",
    overflow: "auto" as const,
    paddingRight: 4,
  },
  logEntry: {
    borderLeft: "3px solid #2563eb",
    background: "#f4f6fb",
    padding: ".25rem .45rem",
    borderRadius: ".3rem",
    fontSize: ".72rem",
    lineHeight: 1.3,
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    columnGap: ".4rem",
    alignItems: "baseline",
  },
  logEntryTimestamp: {
    fontSize: ".65rem",
    color: "#6b7280",
    fontVariantNumeric: "tabular-nums" as const,
  },
  logEntryBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".1rem",
  },
  emptyState: {
    border: "1px dashed #d1d5db",
    borderRadius: ".75rem",
    padding: "1rem",
    color: "#6b7280",
    background: "#f9fafb",
    textAlign: "center" as const,
  },
};
