export const projectBlockStyles = {
  container: {
    marginTop: ".55rem",
    borderTop: "1px solid #e5e7eb",
    paddingTop: ".45rem",
  },
  header: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "center" as const,
    gap: ".4rem",
  },
  name: {
    fontSize: ".65rem",
    fontWeight: 600,
    lineHeight: 1.2,
  },
  scoreBadge: {
    fontSize: ".55rem",
  },
  detailsBtn: {
    fontSize: ".55rem",
    padding: ".28rem .55rem",
    lineHeight: 1.1,
    background: "#2563eb",
    color: "#fff",
    fontWeight: 600,
    border: "1px solid #1d4ed8",
    borderRadius: 4,
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(0,0,0,0.15)",
    transition: "background .15s, box-shadow .15s, transform .12s",
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 4,
    position: "relative" as const,
  },
  pathRow: {
    marginTop: ".35rem",
    display: "flex",
    alignItems: "center" as const,
    gap: ".35rem",
  },
  pathInput: (modified: boolean) => ({
    fontSize: ".6rem",
    padding: ".25rem .35rem",
    border: modified ? "1px solid #f59e0b" : "1px solid #d1d5db",
    background: modified ? "#fff7ed" : "white",
    borderRadius: 4,
    flex: 1,
    minWidth: 140,
    color: modified ? "#7c2d12" : "#111827",
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    letterSpacing: 0.2,
  }),
  modifiedBadge: {
    fontSize: ".5rem",
    background: "#fef3c7",
    border: "1px solid #fcd34d",
    padding: "2px 4px",
    borderRadius: 3,
    color: "#92400e",
    whiteSpace: "nowrap" as const,
  },
} as const;
