export const workflowEditorStyles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  metaRow: {
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap" as const,
  },
  metaField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".25rem",
    flex: "1 1 220px",
  },
  metaInput: {
    borderRadius: ".5rem",
    border: "1px solid #d1d5db",
    padding: ".45rem .65rem",
    fontSize: ".95rem",
  },
  editorBody: {
    display: "grid",
    gridTemplateColumns: "minmax(320px, 1.35fr) minmax(420px, 2.65fr)",
    gap: "1rem",
  },
  listPane: {
    border: "1px solid #e5e7eb",
    borderRadius: ".75rem",
    padding: "1rem",
    background: "#fff",
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
    maxHeight: "520px",
    overflow: "auto" as const,
  },
  listHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: ".5rem",
  },
  list: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".5rem",
  },
  listItem: (active: boolean) => ({
    borderRadius: ".65rem",
    border: active ? "2px solid #2563eb" : "1px solid #e5e7eb",
    background: active ? "#eff6ff" : "#f9fafb",
    padding: ".65rem",
    display: "flex",
    flexDirection: "column" as const,
    gap: ".35rem",
    cursor: "pointer",
  }),
  listItemHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: ".5rem",
  },
  listItemMeta: {
    display: "flex",
    gap: ".35rem",
    alignItems: "center",
    fontSize: ".75rem",
    color: "#4b5563",
  },
  listItemActions: {
    display: "flex",
    gap: ".35rem",
    flexWrap: "wrap" as const,
  },
  iconButton: (tone: "default" | "danger") => {
    const palette = {
      default: {
        background: "transparent",
        color: "#1f2937",
      },
      danger: {
        background: "transparent",
        color: "#dc2626",
      },
    } as const;
    const { background, color } = palette[tone];
    return {
      background,
      border: "1px solid transparent",
      color,
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: "2rem",
      height: "2rem",
      borderRadius: "50%",
      fontSize: "1rem",
      lineHeight: 1,
      padding: 0,
      outline: "none",
      boxShadow: "none",
    } as const;
  },
  listSecondary: {
    marginLeft: "1rem",
    paddingLeft: ".75rem",
    borderLeft: "2px dashed #d1d5db",
    display: "flex",
    flexDirection: "column" as const,
    gap: ".5rem",
  },
  addRow: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".5rem",
    width: "100%",
  },
  select: {
    borderRadius: ".5rem",
    border: "1px solid #d1d5db",
    padding: ".4rem .55rem",
    fontSize: ".9rem",
    width: "100%",
  },
  addButton: {
    width: "100%",
  },
  formPane: {
    border: "1px solid #e5e7eb",
    borderRadius: ".75rem",
    padding: "1rem",
    background: "#fff",
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  formSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".5rem",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: ".65rem",
  },
  field: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".25rem",
  },
  label: {
    fontSize: ".8rem",
    fontWeight: 600,
    color: "#374151",
  },
  input: {
    borderRadius: ".5rem",
    border: "1px solid #d1d5db",
    padding: ".45rem .6rem",
    fontSize: ".95rem",
  },
  textarea: {
    borderRadius: ".5rem",
    border: "1px solid #d1d5db",
    padding: ".5rem .6rem",
    fontSize: ".95rem",
    minHeight: "120px",
    resize: "vertical" as const,
  },
  checkboxRow: {
    display: "flex",
    gap: ".45rem",
    alignItems: "center",
  },
  checkboxInput: {
    width: "1rem",
    height: "1rem",
    borderRadius: ".25rem",
    border: "1px solid #9ca3af",
    accentColor: "#2563eb",
    background: "#fff",
  },
  helperText: {
    fontSize: ".7rem",
    color: "#6b7280",
  },
  readOnlyBadge: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: ".65rem",
    background: "#f3f4f6",
    color: "#1f2937",
    fontWeight: 600,
    fontSize: ".85rem",
    padding: ".35rem .65rem",
  },
  placeholder: {
    color: "#6b7280",
    fontStyle: "italic",
    padding: "1rem",
    border: "1px dashed #d1d5db",
    borderRadius: ".75rem",
    background: "#f9fafb",
  },
};
