export const zipFolderPickerStyles = {
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
    zIndex: 50,
  },
  dialog: {
    background: "#fff",
    width: "min(720px, 100%)",
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column" as const,
    borderRadius: ".75rem",
    boxShadow: "0 10px 25px -5px rgba(0,0,0,0.25)",
    overflow: "hidden",
  },
  header: {
    padding: ".85rem 1rem",
    borderBottom: "1px solid #e5e7eb",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
  },
  title: { margin: 0, fontSize: "1rem" },
  body: {
    padding: "1rem",
    flex: 1,
    overflow: "auto",
    display: "flex",
    gap: "1rem",
  },
  tree: {
    flex: 1,
    fontSize: ".8rem",
    lineHeight: 1.3,
  },
  footer: {
    padding: ".85rem 1rem",
    borderTop: "1px solid #e5e7eb",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    flexWrap: "wrap" as const,
  },
  pathPreview: {
    fontSize: ".7rem",
    background: "#f3f4f6",
    padding: ".4rem .6rem",
    borderRadius: ".4rem",
    wordBreak: "break-all" as const,
    flex: 1,
  },
  nodeRow: {
    display: "flex",
    alignItems: "center",
    gap: ".4rem",
    cursor: "pointer",
    padding: ".25rem .35rem",
    borderRadius: ".35rem",
    userSelect: "none" as const,
  },
  nodeRowActive: {
    background: "#2563eb",
    color: "#fff",
  },
  nodeRowFile: {
    opacity: 0.65,
    cursor: "default",
  },
  disclosure: {
    width: 14,
    textAlign: "center" as const,
    fontSize: ".65rem",
  },
  breadcrumb: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: ".35rem",
    fontSize: ".65rem",
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  breadcrumbItem: {
    display: "flex",
    alignItems: "center",
    gap: ".25rem",
  },
  inlineContainer: {
    border: "1px solid #e5e7eb",
    borderRadius: ".5rem",
    padding: ".75rem .75rem .9rem",
    background: "#fff",
    display: "flex",
    flexDirection: "column" as const,
    gap: ".6rem",
    maxHeight: "340px",
    overflow: "hidden",
  },
  inlineScrollArea: {
    overflow: "auto",
    flex: 1,
    border: "1px solid #e5e7eb",
    borderRadius: ".4rem",
    background: "#f9fafb",
    padding: ".25rem",
  },
};
