export const zpStyles = {
  root: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  stepper: {
    display: "flex",
    gap: ".75rem",
    flexWrap: "wrap" as const,
  },
  configForm: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  formRow: {
    display: "flex",
    flexDirection: "column" as const,
    gap: ".35rem",
  },
  inlineFields: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "1rem",
  },
  input: {
    padding: ".6rem .7rem",
    border: "1px solid #d1d5db",
    borderRadius: ".375rem",
    fontSize: ".9rem",
    flex: 1,
    minWidth: "220px",
  },
  uploadZone: {
    border: "2px dashed #d1d5db",
    borderRadius: ".5rem",
    padding: "3rem 1.5rem",
    textAlign: "center" as const,
    background: "#f9fafb",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "1rem",
  },
  uploadHint: {
    fontSize: "1.05rem",
    color: "#6b7280",
    margin: "0 0 .5rem",
  },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    flexWrap: "wrap" as const,
  },
  studentList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  studentCard: {
    border: "1px solid #e5e7eb",
    borderRadius: ".5rem",
    padding: "1rem",
  },
  studentCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "0 0 .75rem",
  },
  matchGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: ".75rem",
  },
  matchItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: ".65rem .7rem",
    background: "#f9fafb",
    borderRadius: ".5rem",
  },
  matchTitle: {
    fontWeight: 500,
    fontSize: ".8rem",
    margin: "0 0 .15rem",
  },
  matchPath: {
    fontSize: ".7rem",
    color: "#6b7280",
    margin: 0,
  },
  matchStatus: {
    display: "flex",
    alignItems: "center",
    gap: ".35rem",
    fontSize: ".75rem",
  },
  processingState: {
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: ".5rem",
    padding: "1.25rem",
    textAlign: "center" as const,
  },
  spinner: {
    border: "2px solid #f3f4f6",
    borderTop: "2px solid #2563eb",
    borderRadius: "50%",
    width: "2rem",
    height: "2rem",
    animation: "spin 1s linear infinite",
    margin: "0 auto 1rem",
  },
  emptyState: {
    textAlign: "center" as const,
    padding: "3rem 0",
    color: "#6b7280",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "1rem",
  },
} as const;
