name: Build Tauri Binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-tauri:
    name: Build desktop binaries
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install frontend dependencies
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref_type != 'tag' || startsWith(github.ref, 'refs/tags/v') }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            webkit2gtk-4.0 \
            libwebkit2gtk-4.0-dev \
            libssl-dev \
            librsvg2-dev

      - name: Build Tauri bundle
        uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: "npm run tauri:build"

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/**
          if-no-files-found: error
