name: Build Tauri Binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-tauri:
    name: Build desktop binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
            bundlePath: src-tauri/target/aarch64-apple-darwin/release/bundle/**
            artifactName: tauri-macos-aarch64
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
            bundlePath: src-tauri/target/x86_64-apple-darwin/release/bundle/**
            artifactName: tauri-macos-x86_64
          - platform: ubuntu-22.04
            args: ""
            bundlePath: src-tauri/target/release/bundle/**
            artifactName: tauri-linux
          - platform: windows-latest
            args: ""
            bundlePath: src-tauri/target/release/bundle/**
            artifactName: tauri-windows
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install frontend dependencies
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref_type != 'tag' || startsWith(github.ref, 'refs/tags/v') }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Build Tauri bundle
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: "npm run tauri:build"
          tagName: app-v__VERSION__
          releaseName: 'Raisin v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.bundlePath }}
          if-no-files-found: error
